# Generated by Django 5.2.15 on 2026-07-04 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0005_ddl_transaction_legs_balanced"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField(db_index=True)),
                ("action_type", models.CharField(max_length=40)),
                ("source_reference", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "primary_instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_actions",
                        to="django_assets.instrument",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="identifier",
            name="corporate_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="identifiers",
                to="django_assets.corporateaction",
            ),
        ),
        migrations.CreateModel(
            name="CryptoMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("network", models.CharField(blank=True, max_length=50)),
                ("contract_address", models.CharField(blank=True, max_length=100)),
                ("is_stablecoin", models.BooleanField(default=False)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_meta",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "pegged_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pegged_cryptos",
                        to="django_assets.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_code", models.CharField(max_length=3, unique=True)),
                (
                    "iso_numeric",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("is_fiat", models.BooleanField(default=True)),
                ("central_bank", models.CharField(blank=True, max_length=100)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_meta",
                        to="django_assets.instrument",
                    ),
                ),
            ],
        ),
    ]
