# Generated by Django 5.2.15 on 2026-07-04 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0006_add_model_corporateaction_currencymeta_cryptometa"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquityMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_meta",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "primary_exchange",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="django_assets.exchange",
                    ),
                ),
            ],
        ),
    ]
