# Generated by Django 5.2.15 on 2026-07-04 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0007_add_model_equitymeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry", models.DateField(db_index=True)),
                (
                    "strike",
                    models.DecimalField(db_index=True, decimal_places=8, max_digits=20),
                ),
                (
                    "right",
                    models.CharField(choices=[("C", "Call"), ("P", "Put")], max_length=1),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("cash", "Cash"),
                            ("basket", "Basket"),
                        ],
                        default="physical",
                        max_length=20,
                    ),
                ),
                (
                    "exercise_style",
                    models.CharField(
                        choices=[
                            ("american", "American"),
                            ("european", "European"),
                            ("bermudan", "Bermudan"),
                        ],
                        default="american",
                        max_length=20,
                    ),
                ),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_meta",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "underlying",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="option_meta_as_underlying",
                        to="django_assets.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "quantity",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "cash_amount",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "cash_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_deliverables",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "corporate_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverable_changes",
                        to="django_assets.corporateaction",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliverable_components",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "option_meta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="django_assets.optionmeta",
                    ),
                ),
            ],
            options={
                "constraints": [
                    # check= (not condition=): Django 4.2 lanes must apply
                    # this migration; 5.x only deprecates the old kwarg.
                    models.CheckConstraint(
                        check=models.Q(
                            models.Q(
                                ("cash_amount__isnull", True),
                                ("cash_currency__isnull", True),
                                ("instrument__isnull", False),
                                ("quantity__isnull", False),
                            ),
                            models.Q(
                                ("cash_amount__isnull", False),
                                ("cash_currency__isnull", False),
                                ("instrument__isnull", True),
                                ("quantity__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="deliverable_either_instrument_or_cash",
                    )
                ],
            },
        ),
    ]
