# Generated by Django 5.2.15 on 2026-07-04 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0008_add_model_optionmeta_deliverable"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtype", models.CharField(blank=True, db_index=True, max_length=40)),
                ("allows_short", models.BooleanField(default=False)),
                ("allows_margin", models.BooleanField(default=False)),
                (
                    "is_tax_advantaged",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "allows_reconciliation",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("tax_treatment", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brokerage_profile",
                        to="django_assets.account",
                    ),
                ),
            ],
        ),
    ]
