# Generated by Django 5.2.15 on 2026-07-04 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0009_add_model_accountprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_broker", models.SlugField()),
                ("schema_document_kind", models.SlugField()),
                ("schema_format_kind", models.CharField(max_length=20)),
                ("schema_version", models.CharField(max_length=20)),
                (
                    "period_start",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("period_end", models.DateField(blank=True, db_index=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("transaction_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="django_assets.account",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(blank=True, default=list)),
                ("kind", models.CharField(max_length=40)),
                ("source_reference", models.CharField(blank=True, max_length=200)),
                ("note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="django_assets.importbatch",
                    ),
                ),
                (
                    "matched_legs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reconciliation_lines",
                        to="django_assets.transactionleg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("source_data", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_imports",
                        to="django_assets.importbatch",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_meta",
                        to="django_assets.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=[
                    "schema_broker",
                    "schema_document_kind",
                    "schema_format_kind",
                    "schema_version",
                ],
                name="importbatch_schema_key_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="importline",
            constraint=models.UniqueConstraint(
                fields=("batch", "line_number"), name="uniq_line_number_per_batch"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionimport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("batch", "external_id"),
                name="uniq_external_id_per_batch",
            ),
        ),
    ]
