# Generated by Django 5.2.15 on 2026-07-04 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0010_add_import_management"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportLineProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score_total", models.FloatField()),
                ("score_breakdown", models.JSONField(default=dict)),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "proposal_group",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("compound_kind", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                (
                    "candidate_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dedup_proposals",
                        to="django_assets.transaction",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="django_assets.importline",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["line", "rank"], name="django_asse_line_id_72f0e2_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("line", "candidate_transaction"),
                        name="uniq_proposal_line_candidate",
                    )
                ],
            },
        ),
    ]
