# Generated by Django 5.2.15 on 2026-07-04 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0011_add_model_importlineproposal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisclosureEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("source_reference", models.CharField(blank=True, max_length=200)),
                ("disclosed_at", models.DateTimeField(auto_now_add=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("snapshot_before", models.JSONField()),
                ("note", models.TextField(blank=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disclosure_events",
                        to="django_assets.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["disclosed_at", "id"],
            },
        ),
    ]
