# Generated by Django 5.2.15 on 2026-07-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0017_ddl_virtual_entries_balanced"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acquired_at", models.DateTimeField()),
                ("quantity", models.DecimalField(decimal_places=18, max_digits=40)),
                (
                    "quantity_remaining",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                ("cost_basis", models.DecimalField(decimal_places=18, max_digits=40)),
                (
                    "cost_basis_remaining",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                (
                    "direction",
                    models.CharField(choices=[("long", "Long"), ("short", "Short")], max_length=5),
                ),
                ("rollover_linked", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="django_assets.account",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "opened_by_leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_lots",
                        to="django_assets.transactionleg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=40)),
                (
                    "ratio",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                (
                    "quantity_before",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                (
                    "quantity_after",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                ("basis_before", models.DecimalField(decimal_places=18, max_digits=40)),
                ("basis_after", models.DecimalField(decimal_places=18, max_digits=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="django_assets.lot",
                    ),
                ),
                (
                    "source_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_assets.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=18, max_digits=40)),
                ("proceeds", models.DecimalField(decimal_places=18, max_digits=40)),
                (
                    "basis_recovered",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                (
                    "realized_gain",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                (
                    "term",
                    models.CharField(choices=[("short", "Short"), ("long", "Long")], max_length=5),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "closing_leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_matches",
                        to="django_assets.transactionleg",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="django_assets.lot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaleLotScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marked_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="django_assets.account",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="django_assets.instrument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WashSaleAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disallowed_loss",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "loss_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wash_sale_adjustments",
                        to="django_assets.lotmatch",
                    ),
                ),
                (
                    "replacement_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wash_sale_additions",
                        to="django_assets.lot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConversionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_quantity",
                    models.DecimalField(decimal_places=18, max_digits=40),
                ),
                ("to_quantity", models.DecimalField(decimal_places=18, max_digits=40)),
                (
                    "source",
                    models.CharField(
                        choices=[("metadata", "Metadata"), ("manual", "Manual")],
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "from_instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "to_instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_links",
                        to="django_assets.transaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("transaction",), name="uniq_conversion_link")
                ],
            },
        ),
        migrations.CreateModel(
            name="ExerciseLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("metadata", "Metadata"), ("manual", "Manual")],
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "delivered_leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_links",
                        to="django_assets.transactionleg",
                    ),
                ),
                (
                    "option_instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_links",
                        to="django_assets.transaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transaction", "delivered_leg"),
                        name="uniq_exercise_link",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["account", "instrument", "acquired_at"], name="lot_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stalelotscope",
            constraint=models.UniqueConstraint(
                fields=("account", "instrument"), name="uniq_stale_scope"
            ),
        ),
    ]
