# Generated by Django 5.2.15 on 2026-07-05 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0019_ddl_lot_conservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stalelotscope",
            name="account",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_assets.account",
            ),
        ),
        migrations.AlterField(
            model_name="stalelotscope",
            name="instrument",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="django_assets.instrument",
            ),
        ),
    ]
