# Generated by Django 5.2.15 on 2026-07-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0020_stale_scope_no_db_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateActionProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement_date", models.DateField(db_index=True)),
                ("source_reference", models.CharField(blank=True, max_length=200)),
                ("action_kind", models.CharField(max_length=20)),
                (
                    "from_quantity",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True),
                ),
                (
                    "to_quantity",
                    models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_action_proposals",
                        to="django_assets.account",
                    ),
                ),
                (
                    "booked_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_assets.transaction",
                    ),
                ),
                (
                    "from_instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="django_assets.instrument",
                    ),
                ),
                (
                    "to_instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="django_assets.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["statement_date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "fingerprint"),
                        name="uq_caproposal_account_fingerprint",
                    )
                ],
            },
        ),
    ]
