# Generated by Django 5.2.15 on 2026-07-05 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_assets", "0021_add_model_corporateactionproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("proposed_at_date", models.DateField(db_index=True)),
                ("legs", models.JSONField(blank=True, default=list)),
                ("proposed_name", models.CharField(blank=True, max_length=200)),
                ("structure", models.CharField(blank=True, max_length=30)),
                ("horizon", models.CharField(blank=True, max_length=20)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                (
                    "booked_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="django_assets.trade",
                    ),
                ),
                (
                    "event_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="django_assets.transaction",
                    ),
                ),
                (
                    "target_trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="django_assets.trade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["proposed_at_date", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "fingerprint"),
                        name="uniq_tradeproposal_user_fingerprint",
                    )
                ],
            },
        ),
    ]
