import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newContext({ viewport: { width: 1440, height: 900 } }).then(c => c.newPage());
page.on('pageerror', e => console.log('PAGEERROR:', e.message));
page.on('requestfailed', r => console.log('REQFAIL:', r.url(), r.failure()?.errorText));
page.on('response', r => { if (r.url().includes('/tracker/analytics')) console.log('RESP', r.status(), r.url()); });
await page.goto('http://127.0.0.1:8642/tracker/analytics/', { waitUntil: 'networkidle' });
console.log('htmx:', await page.evaluate(() => window.htmx?.version || 'MISSING'));
await page.locator('input[name=goal]').fill('500');
await page.waitForTimeout(3000);
console.log('after fill URL:', page.url(), 'goal-line:', await page.locator('line.goal-line').count());
await page.locator('.switch').click();
await page.waitForTimeout(2500);
console.log('after switch URL:', page.url(), 'bars:', await page.locator('rect.bar').count(), 'goal-line:', await page.locator('line.goal-line').count());
await page.locator('.toggle-pill a:has-text("Monthly")').click();
await page.waitForTimeout(2500);
const label = await page.locator('.goal-field').innerText();
console.log('after monthly URL:', page.url(), 'goal label:', JSON.stringify(label));
await page.screenshot({ path: 'goalprobe3.png', fullPage: true });
await browser.close();
